### ISSUE TITLE
Update dependency install instructions

### ISSUE THREAD

**Issue by humphd** [JiaHua-Zou/Jia_SSG#1]
In the `README` you mention needing to do the following:

```
$ npm install fs-extra yargs
```

Because you already list these dependencies in your `package.json`, using `npm install` is enough (i.e., you don't need to explicitly mention the dependencies to install, it will read them from the package file).

**Comment by lmpham1** [comment]
for some reasons `npm install` doesn't seem to be working for me when I cloned this project. When I run the program after `npm install` , it says I'm missing `fs-extra` module, which is already listed in package.json. Installing it manually works normally. I've noticed another student on Slack is getting this issue as well

**Comment by humphd** [comment]
It looks like `npm install` is failing to parse the `package.json` file and giving up, so no `node_modules` folder gets created.  The fix here is to correct these warnings, especially the version:

```
$ npm install
npm WARN Invalid version: "0.1v"
npm WARN Jia_SSG No description
npm WARN Jia_SSG No repository field.
npm WARN Jia_SSG No README data
npm WARN Jia_SSG No license field.

up to date in 1.285s
found 0 vulnerabilities
```

Also, remove ` "preferGlobal": true,` from `package.json`.  We don't want to use global modules when we can use local.

**Comment by JiaHua-Zou** [comment]
I have deleted the ``` npm install fs-extra yargs``` from the README.md.
I have change the version from ```0.1v``` to  ```1.0.0``` in the ```package.json``` file.

**Comment by humphd** [comment]
One tip re: versioning.  A change like this is a minor change that doesn't break the functioning of the program.  As such, you want to increase your version to indicate it's a minor, non-breaking change vs. a major, breaking change.  [Semantic versioning](https://semver.org/) helps us do that.

In your case, you could have used `0.1.1` to indicate that this is a newer version of the code, but only a patched update.  The jump to `1.0.0` is more dramatic, and indicates the program has drastically changed.

**Comment by JiaHua-Zou** [comment]
Hello David, When I install the package.json file by default it gave version 1.0.0. I changed that version is 0.1. and that might’ve cause a problem when other users tries to run my program. So I just changed it back to the default value and inserted my program value into my index.js file.   Sent from Mail for Windows From: David HumphreySent: September 17, 2021 10:30 AMTo: JiaHua-Zou/Jia_SSGCc: Jia Hua Zou; State changeSubject: Re: [JiaHua-Zou/Jia_SSG] Update dependency install instructions (#1) One tip re: versioning. A change like this is a minor change that doesn't break the functioning of the program. As such, you want to increase your version to indicate it's a minor, non-breaking change vs. a major, breaking change. Semantic versioning helps us do that.In your case, you could have used 0.1.1 to indicate that this is a newer version of the code, but only a patched update. The jump to 1.0.0 is more dramatic, and indicates the program has drastically changed.—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.  

	
        
		Virus-free. www.avast.com
